[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/catppuccin_latte.toml"
]

[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 0.95
padding = { x = 8, y = 8 }

[font]
size = 13.0

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
