import = [
    "~/.config/alacritty/alacritty-theme/themes/atom_one_light.toml"
]

[window]
startup_mode = "Maximized"
decorations = "Full"
decorations_theme_variant = "Light"

[font]
size = 12

[env]
WINIT_X11_SCALE_FACTOR = "1"
