[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/catppuccin_latte.toml"
]

[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 0.95
padding = { x = 8, y = 8 }

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
