[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/github_light_default.toml"
]

[window]
startup_mode = "Maximized"
decorations = "Full"
decorations_theme_variant = "Light"

[font]
size = 13.0

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
